[package]
org = "Orchestro"
name = "service_gateway_cell"
version = "1.0.0"
authors = ["tkt-codex"]

[[dependency]]
org = "Orchestro"
name = "cli_microservice_cell"
version = "1.0.0"

[[dependency]]
org = "Orchestro"
name = "core_platform_cell"
version = "1.0.0"

[[dependency]]
org = "Orchestro"
name = "db_cell"
version = "1.0.0"

[[dependency]]
org = "Orchestro"
name = "monitoring_observability_cell"
version = "1.0.0"

[[dependency]]
org = "Orchestro"
name = "reliability_load_management_cell"
version = "1.0.0"

[build-options]
observabilityIncluded = true

