[service]
name = "service_gateway"
version = "0.1.0"

[network]
port = 9091
protocol = "http"

[dependencies]
cli_microservice_cell = "http://localhost:8081"
core_platform_cell = "http://localhost:8082"
db_cell = "http://localhost:8083"
monitoring_observability_cell = "http://localhost:8085"
reliability_load_management_cell = "http://localhost:8084"

[logging]
level = "INFO"

# Configuration for service endpoints
serviceGatewayPort = 9091
corePlatformServiceURL = "http://localhost:8082"
reliabilityServiceURL = "http://localhost:8084"
observabilityServiceURL = "http://localhost:8085"
cliMicroserviceURL = "http://localhost:8081"
dbServiceURL = "http://localhost:8083"
