[package]
org = "distributed_microservice_orchestration_platform"
name = "cli_microservice_cell"
version = "1.0.0"
authors = ["Thenuja_Dulwana"]
distribution = "2201.10.0"

[build-options]
observabilityIncluded = true