[service]
name = "cli_microservice"
version = "1.0.0"

[network]
port = 8081
protocol = "http"

[dependencies]
core_platform_cell = "http://localhost:8082"
service_gateway_cell = "http://localhost:8080"

[logging]
level = "INFO"

