[service]
name = "core_platform"
version = "0.1.0"

[network]
port = 8082
protocol = "http"

[dependencies]
db_cell = "http://localhost:8083"
service_gateway_cell = "http://localhost:8080"
reliability_load_management_cell = "http://localhost:8084"

[logging]
level = "INFO"
