[package]
org = "Orchestro"
name = "db_cell"
version = "1.0.0"
authors = ["Thenuja_Dulwana"]

[[dependency]]
org = "Orchestro"
name = "core_platform_cell"
version = "1.0.0"

[[dependency]]
org = "Orchestro"
name = "monitoring_observability_cell"
version = "1.0.0"

[build-options]
observabilityIncluded = true
