[package]
org = "Orchestro"
name = "db_cell"
version = "0.1.0"
distribution = "2201.10.2"
authors = ["tkt-codex"]


[[dependency]]
org = "Orchestro"
name = "core_platform_cell"
version = "0.1.0"

[[dependency]]
org = "Orchestro"
name = "monitoring_observability_cell"
version = "0.1.0"

[[dependency]]
org = "Orchestro"
name = "reliability_cell"
version = "0.1.0"

[[platform.java11.dependency]]
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.26"


[build-options]
observabilityIncluded = true
