[server]
host = "localhost"
port = 8080

[database]
type = "postgres"
host = "localhost"
port = 5432
name = "task_management_db"
user = "db_user"
password = "db_password"

[logging]
level = "info"
file = "/var/log/task_management_service.log"

[security]
jwt_secret = "your_jwt_secret_key"
token_expiry = 3600

[services]
user_service_url = "http://localhost:8081"
notification_service_url = "http://localhost:8082"

