[service]
name = "monitoring_observability"
version = "0.1.0"

[network]
port = 8085
protocol = "http"

[dependencies]
db_cell = "http://localhost:8083"
reliability_load_management_cell = "http://localhost:8084"

[logging]
level = "INFO"
